GDC-Level-9-Milestone-master/task_manager/urls.py
from django.contrib import admin
from django.urls import include, path

from .views import UserLoginView, UserCreateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("task/", include('tasks.urls')),
    path('user/signup/', UserCreateView.as_view()),
    path('user/login/', UserLoginView.as_view()),
    path('', UserLoginView.as_view()),
    path('user/logout/', LogoutView.as_view())
]

GDC-Level-9-Milestone-master/tasks/urls.py
from django.urls import path
from . import views
from . import api_views

from rest_framework import routers
router = routers.SimpleRouter()
router.register('api/list', api_views.TaskViewSet)
router.register('api/history', api_views.HistoryViewSet)
from . import tasks

urlpatterns = [
    path('new/', views.TaskCreateView.as_view()),
    path('<int:pk>/update/', views.TaskUpdateView.as_view()),
    path('<int:pk>/delete/', views.DeleteTaskView.as_view()),
    path('list/', views.TaskListView.as_view()),
    path('list/pending/', views.TaskListView.as_view()),
    path('list/completed/', views.TaskListView.as_view()),
    # path('email/', tasks.mail),
    path('set_mail_time/', views.TaskReminderCreateView.as_view()),
    path('<pk>/edit_mail_time/', views.TaskReminderUpdateView.as_view()),
] + router.urls

GDC-Level-9-Milestone-master/tasks/models.py
from django.db import models
from django.contrib.auth.models import User

STATUS_CHOICES = (
    ("PENDING", "PENDING"),
    ("IN_PROGRESS", "IN_PROGRESS"),
    ("COMPLETED", "COMPLETED"),
    ("CANCELLED", "CANCELLED"),
)

class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    completed = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now=True)
    deleted = models.BooleanField(default=False)
    user = models.ForeignKey(User , on_delete=models.CASCADE , null=True, blank=True)
    priority = models.IntegerField(null=True)
    status = models.CharField(max_length=100, choices=STATUS_CHOICES, default=STATUS_CHOICES[0][0])

    def __str__(self):
        return self.title

class TaskHistory(models.Model):
    status = models.CharField(max_length=100, choices=STATUS_CHOICES, default=STATUS_CHOICES[0][0])
    created_date = models.DateTimeField(auto_now=True)
    task = models.ForeignKey(Task , on_delete=models.CASCADE)

class TaskReminder(models.Model):
    reminder_time = models.TimeField(blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

GDC-Level-9-Milestone-master/task_manager/views.py
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = "p-label rounded"
        self.fields['password1'].widget.attrs['class'] = "p-label rounded"
        self.fields['password2'].widget.attrs['class'] = "p-label rounded"

class UserCreateView(CreateView):
    form_class = UserForm
    template_name = "user_create.html"
    success_url = "/user/login/"

class UserLoginView(LoginView):
    template_name = "user_login.html"

GDC-Level-9-Milestone-master/tasks/views.py
from django.forms import ModelForm
from django.shortcuts import redirect
from .models  import Task , TaskReminder
from django.views.generic.edit import CreateView, UpdateView, DeleteView, ModelFormMixin
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin


class AuthorisedTaskManager(LoginRequiredMixin):
    def get_queryset(self):
        return Task.objects.filter(deleted=False, user=self.request.user)

class TaskReminderUpdateView(UpdateView):
    model = TaskReminder
    fields = ['reminder_time']
    template_name = "task/reminder_form.html"
    success_url  = "/task/list/"

class TaskReminderCreateView(AuthorisedTaskManager, CreateView):
    model = TaskReminder
    fields = ['reminder_time']
    template_name = "task/reminder_form.html"
    success_url  = "/task/list/"
    def form_valid(self, form):
        print(form.cleaned_data.get('reminder_time'))
        self.object = form.save()
        self.object.user=self.request.user
        return super().form_valid(form)

class TaskCreateForm(ModelForm):
    class Meta:
        model = Task
        fields = ("title", "description", "priority", "completed")
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['class'] = 'p-label rounded-lg'
        self.fields['title'].widget.attrs['autofocus'] = True
        self.fields['description'].widget.attrs['class'] = 'p-label rounded-lg'
        self.fields['description'].widget.attrs['rows'] = '8'
        self.fields['priority'].widget.attrs['class'] = 'p-label rounded-lg'
        self.fields['completed'].widget.attrs['class'] = 'rounded'
        
class TaskFormMixin(ModelFormMixin):
    def form_valid(self, form):
        if 'priority' in form.changed_data:
            priority = form.cleaned_data["priority"]
            tasks = Task.objects.filter(completed=False, deleted=False)
            objs = []
            same_priority_task = tasks.filter(priority=priority)
            while same_priority_task.exists():
                task = same_priority_task[0]
                task.priority = priority + 1
                objs.append(task)
                priority +=1
                same_priority_task = tasks.filter(priority=priority)

            Task.objects.bulk_update(objs, ['priority'])

        self.object = form.save()
        self.object.user  = self.request.user
        self.object.save()
        return redirect(self.get_success_url())

class TaskCreateView(TaskFormMixin, AuthorisedTaskManager, CreateView):
    form_class = TaskCreateForm
    template_name = "task/task_form.html"
    success_url  = "/task/list/"

class TaskUpdateView(TaskFormMixin, AuthorisedTaskManager, UpdateView):
    model = Task
    form_class = TaskCreateForm
    template_name = "task/task_form.html"
    success_url  = "/task/list/"

class DeleteTaskView(AuthorisedTaskManager, DeleteView):
    model = Task
    success_url  = "/task/list/"

class TaskListView(AuthorisedTaskManager, ListView):
    queryset = Task.objects.filter(deleted=False)
    template_name = "task/list.html"
    context_object_name = "tasks"
    paginate_by = 5
    
    def get_queryset(self):
        tasks = Task.objects.filter(deleted=False, user=self.request.user).order_by('priority')
        if self.request.path == "/task/list/completed/":
            tasks = tasks.filter(completed=True)
        elif self.request.path == "/task/list/pending/":
            tasks = tasks.filter(completed=False)
        return tasks

GDC-Level-9-Milestone-master/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Task Manager</title>
    <link
      rel="icon"
      href='data:image/svg+xml;utf-8,
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="h-5 w-5"
      viewBox="0 0 20 20"
      fill="currentColor"
    >
      <path d="M9 2a1 1 0 000 2h2a1 1 0 100-2H9z" />
      <path
        fill-rule="evenodd"
        d="M4 5a2 2 0 012-2 3 3 0 003 3h2a3 3 0 003-3 2 2 0 012 2v11a2 2 0 01-2 2H6a2 2 0 01-2-2V5zm9.707 5.707a1 1 0 00-1.414-1.414L9 12.586l-1.293-1.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
        clip-rule="evenodd"
      />
    </svg>
    '
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    />
    <link rel="stylesheet" href="{% static 'task/app.css' %}" />
  </head>
  <body>
    <div class="app">{% block content %} {% endblock %}</div>
  </body>
  <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
</html>

GDC-Level-9-Milestone-master/templates/task/list.html
{% extends 'base.html' %} {% block content %}
<div class="title-wrapper">
  <h1 class="title">Hi {{request.user.username}}</h1>
  <form action="/user/logout/" method="post">
    {% csrf_token %}
    <input type="submit" value="Log out" style="color: red" />
  </form>
</div>

<p class="mt-6">
  {% if request.user.taskreminder_set.first %}
  <a href="/task/{{request.user.taskreminder_set.first.id}}/edit_mail_time/"
    >Daily Report Time</a
  >
  {%else%}
  <a href="/task/set_mail_time/">Set Daily Report Time</a>
  {%endif%}
  <!-- {% if request.path == "/task/list/" %} {{c_t.count}} of {{tasks.all.count}}
  tasks completed {%endif%} -->
</p>

<div class="category-container">
  <a href="/task/list/"><p class="rounded-full category-title">All</p></a>
  <a href="/task/list/pending/"
    ><p class="rounded-full category-title">Pending</p></a
  >
  <a href="/task/list/completed/"
    ><p class="rounded-full category-title">Completed</p></a
  >
</div>

{% for task in tasks %}
<div class="task-container rounded-lg">
  <div class="task-info">
    {% if task.completed %}
    <p class="task-title" style="color: red; text-decoration: line-through">
      {{task.title}}
    </p>
    <p style="color: #9b9b9b">{{task.created_date|date:"D j M"}}</p>
    {%else%}
    <p class="task-title">{{task.title}}</p>
    <p style="color: #717272; font-weight: 400">
      {{task.created_date|date:"D j M"}}
    </p>
    {%endif%}
  </div>
  <div class="task-actions">
    <a class="task-links" href="/task/{{task.id}}/update/">
      <!-- Edit SVG Icon -->
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="h-8 w-8 rounded-lg"
        fill="none"
        viewBox="0 0 24 24"
        stroke="white"
        style="background-color: rgb(34, 201, 178); padding: 5px"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"
        />
      </svg>
      <!--  -->
    </a>

    <form method="post" action="/task/{{task.id}}/delete/">
      {% csrf_token %}
      <button
        class="task-links"
        type="submit"
        onclick="return confirm('Are you sure you want to delete this?')"
      >
        <!-- Delete SVG Icon -->
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-8 w-8 rounded-lg"
          fill="none"
          viewBox="0 0 24 24"
          stroke="white"
          style="background-color: red; padding: 5px"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
          />
        </svg>
        <!--  -->
      </button>
    </form>
  </div>
</div>

{%endfor%}
<form action="/task/new/">
  <button type="submit" class="button mt-4 rounded-lg">Add</button>
</form>
{% endblock content %}

GDC-Level-9-Milestone-master/templates/task/reminder_form.html
{% extends 'base.html' %} {% block content %}
<form method="post">
  <p>Enter Time in 24-hour format</p>
  <p>Eg :- 11:30 for 11:30 am, 21:00 for 9 pm</p>
  <br />
  {% csrf_token %} {{form.as_p}}
  <br />
  <button type="submit" value="Set">SET</button>
</form>
{%endblock content%}

GDC-Level-9-Milestone-master/templates/task/task_form.html
{% extends 'base.html' %} {% block content %}
<h1 class="title">
  {% if request.path == '/task/new/' %} Create {% else %} Update {% endif %}
  Todo
</h1>
<form action="" method="post">
  {% csrf_token %}
  <p class="mt-12">Title</p>
  {{form.title}}
  <p class="mt-3">Description</p>
  {{form.description}}

  <p class="mt-3">Priority</p>
  {{form.priority}}
  <br />

  <div class="mt-3 checkbox-wrapper">
    {{form.completed}}
    <p class="p-2">Completed</p>
  </div>

  <button type="submit" class="button mt-4 rounded-lg">
    {% if request.path == '/task/new/' %} Add {% else %} Save {% endif %}
  </button>
</form>

{% endblock content %}

GDC-Level-9-Milestone-master/templates/user_create.html
{% extends 'base.html' %} {% block content %}
<h1 class="title">Todo Manager</h1>
<h3 class="mt-6 mb-4">Signup</h3>

<form method="post">
  {{form}} {% csrf_token %} {{form.errors}}

  <br />
  <button type="submit" class="button mt-4 rounded-lg">Signup</button>
</form>
{% endblock content %}

GDC-Level-9-Milestone-master/templates/user_login.html
{% extends 'base.html' %} {% block content %}
<h1 class="title">Todo Manager</h1>
<h3 class="mt-6 mb-4">Login</h3>

<form method="post" action="">
  {% csrf_token %} {{form.errors}}
  <p class="mt-6">Username</p>
  {{form.username}}
  <p class="mt-3">Password</p>
  {{form.password}}
  <br />
  <br />
  <button type="submit" class="button mt-4 rounded-lg">Login</button>
</form>
{% endblock content %}